namespace KuyumHesapWeb.Core.Feature.MovementTypeFeature.Queries.GetById
{
    public class GetByIdMovementTypeQueryResponse
    {
        public int Id { get; set; }
        /// <summary>
        /// Hareket tipi kodu (örn: SATIS, ALIS, TAHSILAT vb.)
        /// </summary>
        public string TransactionCode { get; set; } = null!;

        /// <summary>
        /// Hareket tipi adı
        /// </summary>
        public string TransactionName { get; set; } = null!;

        public char GC { get; set; }
        public char SC { get; set; }

        /// <summary>
        /// Hareket tipinin aktiflik durumu
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Hareket tipi ile ilgili açıklama
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Otomatik oluşturulan karşı hareket tipi kimliği
        /// </summary>
        public int? AutoGeneratedTransactionTypeId { get; set; }
    }
}
